import turtle
from turtle import *
from importturtule import turtle_controller


for i in range(1):
    reset()
    right(90)
    forward(50)
    right(90)
    forward(50)
    right(90)
    forward(50)
    right(90)
    forward(50)

reset()

for i in range(10):
    reset()
    pendown()
    turtle.color("red")
    left(90)
    forward(100)
    right(45)
    forward(70)
    right(90)
    forward(70)
    right(45)
    forward(100)
    right(90)
    forward(100)
    turtle.color("brown")
    forward(100)
    right(90)
    forward(25)
    right(90)
    forward(100)
    penup()
    right(90)
    forward(25)
    right(90)
    forward(25)
    pendown()
    right(90)
    forward(25)
    left(90)
    penup()
    forward(25)
    left(90)
    pendown()
    forward(25)
    right(90)
    penup()
    forward(25)
    right(90)
    pendown()
    forward(25)
    right(90)
    penup()
    forward(75)
    right(90)
    forward(25)
    right(90)
    forward(100)
    right(90)
    forward(25)
    right(90)
    forward(100)
    right(90)

reset()